# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lambda_entropy <- function(v_tau, a, b) {
    .Call('mixpack_lambda_entropy', PACKAGE = 'mixpack', v_tau, a, b)
}

lambda_demp <- function(v_tau, a, b) {
    .Call('mixpack_lambda_demp', PACKAGE = 'mixpack', v_tau, a, b)
}

lambda_dempMod <- function(v_tau, a, b) {
    .Call('mixpack_lambda_dempMod', PACKAGE = 'mixpack', v_tau, a, b)
}

lambda_coda <- function(v_tau, a, b) {
    .Call('mixpack_lambda_coda', PACKAGE = 'mixpack', v_tau, a, b)
}

lambda_codaNorm <- function(v_tau, a, b) {
    .Call('mixpack_lambda_codaNorm', PACKAGE = 'mixpack', v_tau, a, b)
}

lambda_prop <- function(v_tau, a, b) {
    .Call('mixpack_lambda_prop', PACKAGE = 'mixpack', v_tau, a, b)
}

omega_const <- function(v_tau, a, b) {
    .Call('mixpack_omega_const', PACKAGE = 'mixpack', v_tau, a, b)
}

omega_prop <- function(v_tau, a, b) {
    .Call('mixpack_omega_prop', PACKAGE = 'mixpack', v_tau, a, b)
}

omega_dich <- function(v_tau, a, b) {
    .Call('mixpack_omega_dich', PACKAGE = 'mixpack', v_tau, a, b)
}

mergeComponents <- function(post, a, b) {
    .Call('mixpack_mergeComponents', PACKAGE = 'mixpack', post, a, b)
}

mergeComponents_mult <- function(post, a, b) {
    .Call('mixpack_mergeComponents_mult', PACKAGE = 'mixpack', post, a, b)
}

#' Merging components step
#' 
#' @param post Matrix with the posterior probabilities
#' @param omega omega function name
#' @param lambda lambda function name
#' @return partition using prop and codaNorm
#' @export
mergeStep <- function(post, omega = "prop", lambda = "coda") {
    .Call('mixpack_mergeStep', PACKAGE = 'mixpack', post, omega, lambda)
}

#' Build a hierchical partition from posterior probabilities
#' 
#' This function applies the methodology described in [citar article]
#' to build a hierarchy of classes using the weights or probabilities 
#' that an element belongs to each class
#' @param tau dataframe of probabilities/weights (\code{tau} must be strictly positive)
#' 
#' @param omega function with two parameters (\code{v_tau}, \code{a}). Parameter 
#' \code{v_tau} is a vector of probabilities, parameter \code{a} is the a selected class.
#'\code{omega}(\code{v_tau}, \code{a}) gives the representativeness of element with
#' probabities \code{v_tau} to class \code{a}
#' 
#' @param lambda function with three parameters (\code{v_tau}, \code{a}, \code{b}).
#' Parameter \code{v_tau} is a vector of probabilities, parameters \code{a} and \code{b}
#' are classes to be combined.
#' @export
get_hierarchical_partition_fast <- function(post, omega = "prop", lambda = "coda") {
    .Call('mixpack_get_hierarchical_partition_fast', PACKAGE = 'mixpack', post, omega, lambda)
}

#' Build a hierchical partition from posterior probabilities
#' 
#' This function applies the methodology described in [citar article]
#' to build a hierarchy of classes using the weights or probabilities 
#' that an element belongs to each class
#' @param tau dataframe of probabilities/weights (\code{tau} must be strictly positive)
#' 
#' @param omega function with two parameters (\code{v_tau}, \code{a}). Parameter 
#' \code{v_tau} is a vector of probabilities, parameter \code{a} is the a selected class.
#'\code{omega}(\code{v_tau}, \code{a}) gives the representativeness of element with
#' probabities \code{v_tau} to class \code{a}
#' 
#' @param lambda function with three parameters (\code{v_tau}, \code{a}, \code{b}).
#' Parameter \code{v_tau} is a vector of probabilities, parameters \code{a} and \code{b}
#' are classes to be combined.
#' @export
get_hierarchical_partition_mult_fast <- function(post, omega = "prop", lambda = "coda") {
    .Call('mixpack_get_hierarchical_partition_mult_fast', PACKAGE = 'mixpack', post, omega, lambda)
}

