# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lambda_entropy <- function(v_tau, a, b) {
    .Call('mixpack_lambda_entropy', PACKAGE = 'mixpack', v_tau, a, b)
}

lambda_demp <- function(v_tau, a, b) {
    .Call('mixpack_lambda_demp', PACKAGE = 'mixpack', v_tau, a, b)
}

lambda_dempMod <- function(v_tau, a, b) {
    .Call('mixpack_lambda_dempMod', PACKAGE = 'mixpack', v_tau, a, b)
}

lambda_coda <- function(v_tau, a, b) {
    .Call('mixpack_lambda_coda', PACKAGE = 'mixpack', v_tau, a, b)
}

lambda_codaNorm <- function(v_tau, a, b) {
    .Call('mixpack_lambda_codaNorm', PACKAGE = 'mixpack', v_tau, a, b)
}

lambda_prop <- function(v_tau, a, b) {
    .Call('mixpack_lambda_prop', PACKAGE = 'mixpack', v_tau, a, b)
}

omega_const <- function(v_tau, a, b) {
    .Call('mixpack_omega_const', PACKAGE = 'mixpack', v_tau, a, b)
}

omega_prop <- function(v_tau, a, b) {
    .Call('mixpack_omega_prop', PACKAGE = 'mixpack', v_tau, a, b)
}

omega_dich <- function(v_tau, a, b) {
    .Call('mixpack_omega_dich', PACKAGE = 'mixpack', v_tau, a, b)
}

mergeComponents <- function(post, a, b) {
    .Call('mixpack_mergeComponents', PACKAGE = 'mixpack', post, a, b)
}

#' Merging components step
#' 
#' @param post Matrix with the posterior probabilities
#' @export
mergeStep_prop_codaNorm <- function(post) {
    .Call('mixpack_mergeStep_prop_codaNorm', PACKAGE = 'mixpack', post)
}

confusion_prop_codaNorm <- function(post, a, b) {
    .Call('mixpack_confusion_prop_codaNorm', PACKAGE = 'mixpack', post, a, b)
}

confusion_const_entropy <- function(post, a, b) {
    .Call('mixpack_confusion_const_entropy', PACKAGE = 'mixpack', post, a, b)
}

confusion_prop_demp <- function(post, a, b) {
    .Call('mixpack_confusion_prop_demp', PACKAGE = 'mixpack', post, a, b)
}

